export class Icons {
	static readonly bookmark = '$(bookmark)'
	static readonly bookmarks = '$(bookmarks)'
	static readonly bookmark_tag = '$(tag)'
	static readonly bookmark_sq = '$(bookmark)'
	static readonly folder = '$(folder)'
	static readonly edit = '$(edit)'
	static readonly delete = '$(trash)'
	static readonly view = '$(eye)'
	static readonly open_folder = '$(folder-opened)'
	static readonly open_folder_green = '$(folder-opened)'
	static readonly filter_all = '$(list-flat)'
	static readonly filter_file = '$(file)'
	static readonly filter_tree = '$(list-tree)'
	static readonly filter_tree_highligh = '$(list-tree)'
	static readonly remove_watcher = '$(eye-closed)'
	static readonly remove_all = '$(clear-all)'
	static readonly import_json = '$(import)'
	static readonly export_json = '$(export)'
	static readonly refresh = '$(refresh)'
	static readonly storage_json = '$(json)'
	static readonly storage_workspace = '$(server)'
}
